// generated by Textmapper; DO NOT EDIT

package ast

import (
	"fmt"

	"github.com/mewspring/demo/dmo"
)

func ToDemoNode(n *Node) DemoNode {
	switch n.Type() {
	case dmo.Command:
		return &Command{n}
	case dmo.CommandTypeEnum:
		return &CommandTypeEnum{n}
	case dmo.EventData:
		return &EventData{n}
	case dmo.EventType:
		return &EventType{n}
	case dmo.File:
		return &File{n}
	case dmo.FileHeader:
		return &FileHeader{n}
	case dmo.FloatLit:
		return &FloatLit{n}
	case dmo.IntLit:
		return &IntLit{n}
	case dmo.NoType:
		return nilInstance
	}
	panic(fmt.Errorf("ast: unknown node type %v", n.Type()))
	return nil
}
