// generated by Textmapper; DO NOT EDIT

package demo

const tmNumClasses = 8

var tmRuneClass = []uint8{
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 4, 5, 6, 1, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7,
}

const tmRuneClassLen = 58
const tmFirstRule = -1

var tmStateMap = []int{
	0,
}

var tmLexerAction = []int8{
	-1, -2, 7, 5, 4, 3, -2, 1, -4, -4, -4, -4, -4, -4, 2, 1, -5, -5, -5, -5, -5,
	-5, -5, 2, -2, -2, -2, -2, -2, -2, -2, 1, -6, -6, -6, -6, -6, -6, -6, -6, -2,
	-2, -2, -2, -2, -2, -2, 6, -2, -2, -2, -2, -2, -2, 2, 6, -3, -3, -3, -3, -3,
	-3, -3, -3,
}
