// generated by Textmapper; DO NOT EDIT

package demo

import (
	"fmt"
)

type NodeType int

type Listener func(t NodeType, offset, endoffset int)

const (
	NoType NodeType = iota
	File            // FileHeader Commands=(Command)*
	FileHeader
	Command // MsgTypeEnum GameTickProgress CommandData?
	MsgTypeEnum
	GameTickProgress
	CommandData // MessageType WParam LParam
	MessageType
	WParam
	LParam
	NodeTypeMax
)

var nodeTypeStr = [...]string{
	"NONE",
	"File",
	"FileHeader",
	"Command",
	"MsgTypeEnum",
	"GameTickProgress",
	"CommandData",
	"MessageType",
	"WParam",
	"LParam",
}

func (t NodeType) String() string {
	if t >= 0 && int(t) < len(nodeTypeStr) {
		return nodeTypeStr[t]
	}
	return fmt.Sprintf("node(%d)", t)
}
