// generated by Textmapper; DO NOT EDIT

package demo

import (
	"fmt"
)

// Token is an enum of all terminal symbols of the demo language.
type Token int

// Token values.
const (
	UNAVAILABLE Token = iota - 1
	EOI
	INVALID_TOKEN
	_NEW_LINE
	INT_LIT_TOK
	FLOAT_LIT_TOK
	COMMA

	NumTokens
)

var tokenStr = [...]string{
	"EOI",
	"INVALID_TOKEN",
	"_NEW_LINE",
	"INT_LIT_TOK",
	"FLOAT_LIT_TOK",
	"COMMA",
}

func (tok Token) String() string {
	if tok >= 0 && int(tok) < len(tokenStr) {
		return tokenStr[tok]
	}
	return fmt.Sprintf("token(%d)", tok)
}
