// generated by Textmapper; DO NOT EDIT

package ast

import (
	"github.com/mewspring/demo/selector"
)

// Interfaces.

type DemoNode interface {
	DemoNode() *Node
}

type NilNode struct{}

var nilInstance = &NilNode{}

// All types implement DemoNode.
func (n Command) DemoNode() *Node          { return n.Node }
func (n CommandData) DemoNode() *Node      { return n.Node }
func (n File) DemoNode() *Node             { return n.Node }
func (n FileHeader) DemoNode() *Node       { return n.Node }
func (n GameTickProgress) DemoNode() *Node { return n.Node }
func (n LParam) DemoNode() *Node           { return n.Node }
func (n MessageType) DemoNode() *Node      { return n.Node }
func (n MsgTypeEnum) DemoNode() *Node      { return n.Node }
func (n WParam) DemoNode() *Node           { return n.Node }
func (NilNode) DemoNode() *Node            { return nil }

// Types.

type Command struct {
	*Node
}

func (n Command) MsgTypeEnum() MsgTypeEnum {
	return MsgTypeEnum{n.Child(selector.MsgTypeEnum)}
}

func (n Command) GameTickProgress() GameTickProgress {
	return GameTickProgress{n.Child(selector.GameTickProgress)}
}

func (n Command) CommandData() (CommandData, bool) {
	field := CommandData{n.Child(selector.CommandData)}
	return field, field.IsValid()
}

type CommandData struct {
	*Node
}

func (n CommandData) MessageType() MessageType {
	return MessageType{n.Child(selector.MessageType)}
}

func (n CommandData) WParam() WParam {
	return WParam{n.Child(selector.WParam)}
}

func (n CommandData) LParam() LParam {
	return LParam{n.Child(selector.LParam)}
}

type File struct {
	*Node
}

func (n File) FileHeader() FileHeader {
	return FileHeader{n.Child(selector.FileHeader)}
}

func (n File) Commands() []Command {
	nodes := n.Children(selector.Command)
	var ret = make([]Command, 0, len(nodes))
	for _, node := range nodes {
		ret = append(ret, Command{node})
	}
	return ret
}

type FileHeader struct {
	*Node
}

type GameTickProgress struct {
	*Node
}

type LParam struct {
	*Node
}

type MessageType struct {
	*Node
}

type MsgTypeEnum struct {
	*Node
}

type WParam struct {
	*Node
}
