// generated by Textmapper; DO NOT EDIT

package ast

import (
	"fmt"

	"github.com/mewspring/demo"
)

func ToDemoNode(n *Node) DemoNode {
	switch n.Type() {
	case demo.Command:
		return &Command{n}
	case demo.CommandTypeEnum:
		return &CommandTypeEnum{n}
	case demo.EventData:
		return &EventData{n}
	case demo.EventType:
		return &EventType{n}
	case demo.File:
		return &File{n}
	case demo.FileHeader:
		return &FileHeader{n}
	case demo.FloatLit:
		return &FloatLit{n}
	case demo.IntLit:
		return &IntLit{n}
	case demo.NoType:
		return nilInstance
	}
	panic(fmt.Errorf("ast: unknown node type %v", n.Type()))
	return nil
}
